-- MySQL Script generated by MySQL Workbench
-- Sun Jun 30 17:05:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema univercity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema univercity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `univercity` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `univercity` ;

-- -----------------------------------------------------
-- Table `univercity`.`type_of_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`type_of_person` (
  `PersonID` INT NOT NULL AUTO_INCREMENT,
  `PersonType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PersonID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO univercity.type_of_person (PersonID, PersonType)
VALUES
(3, 'Curator'),
(4, 'Staff');


-- -----------------------------------------------------
-- Table `univercity`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`person` (
  `personPersonID` INT NOT NULL AUTO_INCREMENT,
  `TypeOfPerson` INT NULL DEFAULT NULL,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `FamilyName` VARCHAR(50) NULL DEFAULT NULL,
  `AlternativeLastName` VARCHAR(500) NULL DEFAULT NULL,
  `Affix` VARCHAR(45) NULL DEFAULT NULL COMMENT 'de, van, van der, etc.',
  `Nickname` VARCHAR(100) NULL DEFAULT NULL,
  `Gender` VARCHAR(45) NULL DEFAULT NULL,
  `Nationality` VARCHAR(100) NULL DEFAULT NULL,
  `Religion` VARCHAR(100) NULL DEFAULT NULL,
  `Status` VARCHAR(100) NULL DEFAULT NULL,
  `Handles` VARCHAR(500) NULL DEFAULT NULL COMMENT 'Longest value in excel file is 475 chars',
  `AVG` VARCHAR(4) NULL DEFAULT NULL COMMENT 'AVG = 0\\nVrij = 1',
  `Faculty` VARCHAR(50) NULL DEFAULT NULL,
  `Rating` INT NULL DEFAULT NULL,
  PRIMARY KEY (`personPersonID`),
  INDEX `person_idx` (`TypeOfPerson` ASC) VISIBLE,
  CONSTRAINT `person`
    FOREIGN KEY (`TypeOfPerson`)
    REFERENCES `univercity`.`type_of_person` (`PersonID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

ALTER TABLE `univercity`.`person`
ADD COLUMN `Faculty` VARCHAR(50) NULL DEFAULT NULL AFTER `AVG`,
ADD COLUMN `Rating` INT NULL DEFAULT NULL AFTER `Faculty`,
ADD COLUMN `AlternativeLastName` VARCHAR(500) NULL AFTER `FamilyName`,
CHANGE COLUMN `Nickname` `Nickname` VARCHAR(100) NULL DEFAULT NULL ;


-- -----------------------------------------------------
-- Table `univercity`.`career`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`career` (
  `CareerID` INT NOT NULL AUTO_INCREMENT,
  `personPersonID` INT NULL DEFAULT NULL,
  `Job` VARCHAR(500) NULL DEFAULT NULL,
  `Location` VARCHAR(500) NULL DEFAULT NULL,
  `Date` VARCHAR(50) NULL DEFAULT NULL,
  `Source` VARCHAR(500) NULL DEFAULT NULL,
  `IsSideJob` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`CareerID`),
  INDEX `personPersonID` (`personPersonID` ASC) VISIBLE,
  CONSTRAINT `career_ibfk_1`
    FOREIGN KEY (`personPersonID`)
    REFERENCES `univercity`.`person` (`personPersonID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`education` (
  `EducationID` INT NOT NULL AUTO_INCREMENT,
  `personPersonID` INT NULL DEFAULT NULL,
  `Subject` VARCHAR(100) NULL DEFAULT NULL,
  `Location` VARCHAR(500) NULL DEFAULT NULL,
  `Date` VARCHAR(50) NULL DEFAULT NULL,
  `Source` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`EducationID`),
  INDEX `personPersonID` (`personPersonID` ASC) VISIBLE,
  CONSTRAINT `education_ibfk_1`
    FOREIGN KEY (`personPersonID`)
    REFERENCES `univercity`.`person` (`personPersonID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`event` (
  `EventID` INT NOT NULL AUTO_INCREMENT,
  `EventType` VARCHAR(45) NOT NULL,
  `EventDate` VARCHAR(20) NULL DEFAULT NULL,
  `EventPlace` VARCHAR(100) NULL DEFAULT NULL,
  `EventRemark` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`EventID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`type_of_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`type_of_location` (
  `LocationID` INT NOT NULL AUTO_INCREMENT,
  `LocationType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`LocationID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO univercity.type_of_relation (RelationType) VALUES
('Ouder'),
('Grootouder'),
('Echtgenoot'),
('Schoonouder'),
('Kind'),
('Verre familie'),
('Zelfde persoon?');


-- -----------------------------------------------------
-- Table `univercity`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`location` (
  `LocationID` INT NOT NULL AUTO_INCREMENT,
  `TypeOfLocation` INT NOT NULL,
  `Country` VARCHAR(100) NULL DEFAULT NULL,
  `City` VARCHAR(100) NULL DEFAULT NULL,
  `Street` VARCHAR(100) NULL DEFAULT NULL,
  `HouseNumber` VARCHAR(10) NULL DEFAULT NULL COMMENT 'VARCHAR to include entries such 10a',
  `Region` VARCHAR(100) NULL DEFAULT NULL,
  `Latitude` FLOAT NULL DEFAULT NULL,
  `Longitude` FLOAT NULL DEFAULT NULL,
  `locationStartDate` VARCHAR(20) NULL DEFAULT NULL,
  `locationEndDate` VARCHAR(20) NULL DEFAULT NULL,
  `ISO_Alpha_3` VARCHAR(3) NULL DEFAULT NULL,
  `locationPersonID` INT NOT NULL,
  PRIMARY KEY (`LocationID`),
  INDEX `TypeOfLocation_location_idx` (`TypeOfLocation` ASC) VISIBLE,
  INDEX `PersonID_location_idx` (`locationPersonID` ASC) VISIBLE,
  CONSTRAINT `PersonID_location`
    FOREIGN KEY (`locationPersonID`)
    REFERENCES `univercity`.`person` (`personPersonID`),
  CONSTRAINT `TypeOfLocation_location`
    FOREIGN KEY (`TypeOfLocation`)
    REFERENCES `univercity`.`type_of_location` (`LocationID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`type_of_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`type_of_source` (
  `SourceID` INT NOT NULL AUTO_INCREMENT,
  `SourceType` VARCHAR(100) NOT NULL,
  `Rating` INT NULL DEFAULT NULL COMMENT 'Score in set [1, 2, 3]\\nExample:\\n - Excel files = 3\\n - OpenArchives = 1',
  PRIMARY KEY (`SourceID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`source` (
  `SourceID` INT NOT NULL AUTO_INCREMENT,
  `SourceType` INT NOT NULL,
  `SourceDate` VARCHAR(20) NULL DEFAULT NULL,
  `PermaLink` VARCHAR(200) NULL DEFAULT NULL,
  `SourceLastChangeDate` DATE NULL DEFAULT NULL,
  `SourceAccessedAt` TIMESTAMP NULL DEFAULT NULL,
  `SourceRemark` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`SourceID`),
  INDEX `source_idx` (`SourceType` ASC) VISIBLE,
  CONSTRAINT `source`
    FOREIGN KEY (`SourceType`)
    REFERENCES `univercity`.`type_of_source` (`SourceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`location_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`location_source` (
  `LocationID` INT NOT NULL,
  `SourceID` INT NOT NULL,
  PRIMARY KEY (`LocationID`),
  INDEX `toSource_idx` (`SourceID` ASC) VISIBLE,
  CONSTRAINT `location_toLocation`
    FOREIGN KEY (`LocationID`)
    REFERENCES `univercity`.`location` (`LocationID`),
  CONSTRAINT `location_toSource`
    FOREIGN KEY (`SourceID`)
    REFERENCES `univercity`.`source` (`SourceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`particularity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`particularity` (
  `ParticularityID` INT NOT NULL AUTO_INCREMENT,
  `personPersonID` INT NULL DEFAULT NULL,
  `Particularity` VARCHAR(500) NULL DEFAULT NULL,
  `Location` VARCHAR(50) NULL DEFAULT NULL,
  `Date` VARCHAR(50) NULL DEFAULT NULL,
  `Source` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`ParticularityID`),
  INDEX `personPersonID` (`personPersonID` ASC) VISIBLE,
  CONSTRAINT `particularity_ibfk_1`
    FOREIGN KEY (`personPersonID`)
    REFERENCES `univercity`.`person` (`personPersonID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`person_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`person_source` (
  `PersonID` INT NOT NULL,
  `SourceID` INT NOT NULL,
  PRIMARY KEY (`PersonID`),
  INDEX `toSource_idx` (`SourceID` ASC) VISIBLE,
  CONSTRAINT `person_toPerson`
    FOREIGN KEY (`PersonID`)
    REFERENCES `univercity`.`person` (`personPersonID`),
  CONSTRAINT `person_toSource`
    FOREIGN KEY (`SourceID`)
    REFERENCES `univercity`.`source` (`SourceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`type_of_expertise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`type_of_expertise` (
  `ExpertiseID` INT NOT NULL AUTO_INCREMENT,
  `ExpertiseType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ExpertiseID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`type_of_faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`type_of_faculty` (
  `FacultyID` INT NOT NULL AUTO_INCREMENT,
  `FacultyType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`FacultyID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`type_of_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`type_of_position` (
  `PositionID` INT NOT NULL AUTO_INCREMENT,
  `PositionType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PositionID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`type_of_profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`type_of_profession` (
  `ProfessionID` INT NOT NULL AUTO_INCREMENT,
  `ProfessionType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ProfessionID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`profession` (
  `ProfessionID` INT NOT NULL AUTO_INCREMENT,
  `TypeOfProfession` INT NULL DEFAULT NULL,
  `TypeOfPosition` INT NULL DEFAULT NULL,
  `TypeOfExpertise` INT NULL DEFAULT NULL,
  `TypeOfFaculty` INT NULL DEFAULT NULL,
  `professionStartDate` VARCHAR(20) NULL DEFAULT NULL,
  `professionEndDate` VARCHAR(20) NULL DEFAULT NULL,
  `professionPersonID` INT NOT NULL,
  PRIMARY KEY (`ProfessionID`),
  INDEX `faculty_idx` (`TypeOfFaculty` ASC) VISIBLE,
  INDEX `position_idx` (`TypeOfPosition` ASC) VISIBLE,
  INDEX `profession_idx` (`TypeOfProfession` ASC) VISIBLE,
  INDEX `expertise_idx` (`TypeOfExpertise` ASC) VISIBLE,
  INDEX `person_profession_idx` (`professionPersonID` ASC) VISIBLE,
  CONSTRAINT `expertise`
    FOREIGN KEY (`TypeOfExpertise`)
    REFERENCES `univercity`.`type_of_expertise` (`ExpertiseID`),
  CONSTRAINT `faculty`
    FOREIGN KEY (`TypeOfFaculty`)
    REFERENCES `univercity`.`type_of_faculty` (`FacultyID`),
  CONSTRAINT `person_profession`
    FOREIGN KEY (`professionPersonID`)
    REFERENCES `univercity`.`person` (`personPersonID`),
  CONSTRAINT `position`
    FOREIGN KEY (`TypeOfPosition`)
    REFERENCES `univercity`.`type_of_position` (`PositionID`),
  CONSTRAINT `profession`
    FOREIGN KEY (`TypeOfProfession`)
    REFERENCES `univercity`.`type_of_profession` (`ProfessionID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`profession_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`profession_source` (
  `ProfessionID` INT NOT NULL,
  `SourceID` INT NOT NULL,
  PRIMARY KEY (`ProfessionID`),
  INDEX `profession_toSource_idx` (`SourceID` ASC) VISIBLE,
  CONSTRAINT `profession_toProfession`
    FOREIGN KEY (`ProfessionID`)
    REFERENCES `univercity`.`profession` (`ProfessionID`),
  CONSTRAINT `profession_toSource`
    FOREIGN KEY (`SourceID`)
    REFERENCES `univercity`.`source` (`SourceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`publication` (
  `PublicationID` INT NOT NULL AUTO_INCREMENT,
  `ExaminationType` INT NULL DEFAULT NULL,
  `Institution` VARCHAR(100) NULL DEFAULT NULL,
  `PublicationDate` DATE NULL DEFAULT NULL,
  `Title` VARCHAR(250) NULL DEFAULT NULL,
  `IsThesis` INT NOT NULL DEFAULT '0' COMMENT '1 = True, dissertation\\n0 = False, NOT a dissertation',
  `publicationPersonID` INT NOT NULL,
  PRIMARY KEY (`PublicationID`),
  INDEX `publication_PersonID_idx` (`publicationPersonID` ASC) VISIBLE,
  CONSTRAINT `publication_PersonID`
    FOREIGN KEY (`publicationPersonID`)
    REFERENCES `univercity`.`person` (`personPersonID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`type_of_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`type_of_relation` (
  `RelationID` INT NOT NULL AUTO_INCREMENT,
  `RelationType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`RelationID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`relation` (
  `RelationID` INT NOT NULL AUTO_INCREMENT,
  `TypeOfRelation` INT NOT NULL,
  `FromPersonID` INT NOT NULL,
  `ToPersonID` INT NOT NULL,
  `LinkClass` INT NULL DEFAULT NULL COMMENT '0 = Potential Link (needs second/human verification)\\n1 = Certain Link',
  `EventID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`RelationID`),
  INDEX `ToPersonID_ptp_idx` (`ToPersonID` ASC) VISIBLE,
  INDEX `FromPersonID_ptp` (`FromPersonID` ASC) VISIBLE,
  INDEX `TypeOfRelation_ptp_idx` (`TypeOfRelation` ASC) VISIBLE,
  INDEX `EventID_idx` (`EventID` ASC) VISIBLE,
  CONSTRAINT `EventID`
    FOREIGN KEY (`EventID`)
    REFERENCES `univercity`.`event` (`EventID`),
  CONSTRAINT `FromPersonID_ptp`
    FOREIGN KEY (`FromPersonID`)
    REFERENCES `univercity`.`person` (`personPersonID`),
  CONSTRAINT `ToPersonID_ptp`
    FOREIGN KEY (`ToPersonID`)
    REFERENCES `univercity`.`person` (`personPersonID`),
  CONSTRAINT `TypeOfRelation_ptp`
    FOREIGN KEY (`TypeOfRelation`)
    REFERENCES `univercity`.`type_of_relation` (`RelationID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univercity`.`relation_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univercity`.`relation_source` (
  `RelationID` INT NOT NULL,
  `SourceID` INT NOT NULL,
  PRIMARY KEY (`RelationID`),
  INDEX `relation_toSource_idx` (`SourceID` ASC) VISIBLE,
  CONSTRAINT `relation_toRelation`
    FOREIGN KEY (`RelationID`)
    REFERENCES `univercity`.`relation` (`RelationID`),
  CONSTRAINT `relation_toSource`
    FOREIGN KEY (`SourceID`)
    REFERENCES `univercity`.`source` (`SourceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
