ALTER TABLE `univercity`.`person`
ADD COLUMN `BirthDate` VARCHAR(50) NULL DEFAULT NULL AFTER `AVG`,
ADD COLUMN `BirthYear` VARCHAR(50) NULL DEFAULT NULL AFTER `BirthDate`;
ADD COLUMN `BirthCountry` VARCHAR(50) NULL DEFAULT NULL AFTER `BirthYear`,
ADD COLUMN `BirthCity` VARCHAR(50) NULL DEFAULT NULL AFTER `BirthCountry`,
ADD COLUMN `BaptizedDate` VARCHAR(50) NULL DEFAULT NULL AFTER `BirthCity`,
ADD COLUMN `DeathDate` VARCHAR(50) NULL DEFAULT NULL AFTER `BaptizedDate`,
ADD COLUMN `DeathCity` VARCHAR(50) NULL DEFAULT NULL AFTER `DeathDate`,
ADD COLUMN `DeathCountry` VARCHAR(50) NULL DEFAULT NULL AFTER `DeathCity`,
ADD COLUMN `Faculty` VARCHAR(50) NULL DEFAULT NULL AFTER `DeathCountry`,
ADD COLUMN `Rating` INT NULL DEFAULT NULL AFTER `Faculty`;
